package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BackupLoadArrangement generated by hbm2java
 */
@Entity
@Table(name="backup_load_arrangement"
    ,catalog="faculty_portal"
)
public class BackupLoadArrangement  implements java.io.Serializable {


     private BackupLoadArrangementId id;
     private Integer semester;
     private String divBatch;
     private Integer roomNo;
     private String subjectName;
     private Integer assignedFaculty;
     private String status;
     private Date approveDate;

    public BackupLoadArrangement() {
    }

	
    public BackupLoadArrangement(BackupLoadArrangementId id, String status) {
        this.id = id;
        this.status = status;
    }
    public BackupLoadArrangement(BackupLoadArrangementId id, Integer semester, String divBatch, Integer roomNo, String subjectName, Integer assignedFaculty, String status, Date approveDate) {
       this.id = id;
       this.semester = semester;
       this.divBatch = divBatch;
       this.roomNo = roomNo;
       this.subjectName = subjectName;
       this.assignedFaculty = assignedFaculty;
       this.status = status;
       this.approveDate = approveDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="year", column=@Column(name="Year", nullable=false, length=10) ), 
        @AttributeOverride(name="empLeaveId", column=@Column(name="EmpLeaveID", nullable=false) ), 
        @AttributeOverride(name="date", column=@Column(name="Date", nullable=false, length=10) ), 
        @AttributeOverride(name="time", column=@Column(name="Time", nullable=false, length=10) ) } )
    public BackupLoadArrangementId getId() {
        return this.id;
    }
    
    public void setId(BackupLoadArrangementId id) {
        this.id = id;
    }

    
    @Column(name="Semester")
    public Integer getSemester() {
        return this.semester;
    }
    
    public void setSemester(Integer semester) {
        this.semester = semester;
    }

    
    @Column(name="DivBatch", length=5)
    public String getDivBatch() {
        return this.divBatch;
    }
    
    public void setDivBatch(String divBatch) {
        this.divBatch = divBatch;
    }

    
    @Column(name="RoomNo")
    public Integer getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(Integer roomNo) {
        this.roomNo = roomNo;
    }

    
    @Column(name="SubjectName", length=50)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    
    @Column(name="AssignedFaculty")
    public Integer getAssignedFaculty() {
        return this.assignedFaculty;
    }
    
    public void setAssignedFaculty(Integer assignedFaculty) {
        this.assignedFaculty = assignedFaculty;
    }

    
    @Column(name="Status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ApproveDate", length=10)
    public Date getApproveDate() {
        return this.approveDate;
    }
    
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }




}


