package hibernate.pojos;
// Generated Apr 2, 2017 5:52:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BackupSubjectPreferencesId generated by hbm2java
 */
@Embeddable
public class BackupSubjectPreferencesId  implements java.io.Serializable {


     private String year;
     private int userId;
     private int subId;

    public BackupSubjectPreferencesId() {
    }

    public BackupSubjectPreferencesId(String year, int userId, int subId) {
       this.year = year;
       this.userId = userId;
       this.subId = subId;
    }
   


    @Column(name="Year", nullable=false, length=10)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }


    @Column(name="UserID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="SubID", nullable=false)
    public int getSubId() {
        return this.subId;
    }
    
    public void setSubId(int subId) {
        this.subId = subId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BackupSubjectPreferencesId) ) return false;
		 BackupSubjectPreferencesId castOther = ( BackupSubjectPreferencesId ) other; 
         
		 return ( (this.getYear()==castOther.getYear()) || ( this.getYear()!=null && castOther.getYear()!=null && this.getYear().equals(castOther.getYear()) ) )
 && (this.getUserId()==castOther.getUserId())
 && (this.getSubId()==castOther.getSubId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getYear() == null ? 0 : this.getYear().hashCode() );
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getSubId();
         return result;
   }   


}


