package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BackupSlotPreference generated by hbm2java
 */
@Entity
@Table(name="backup_slot_preference"
    ,catalog="faculty_portal"
)
public class BackupSlotPreference  implements java.io.Serializable {


     private BackupSlotPreferenceId id;
     private String slot;

    public BackupSlotPreference() {
    }

    public BackupSlotPreference(BackupSlotPreferenceId id, String slot) {
       this.id = id;
       this.slot = slot;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="year", column=@Column(name="Year", nullable=false, length=10) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserID", nullable=false) ) } )
    public BackupSlotPreferenceId getId() {
        return this.id;
    }
    
    public void setId(BackupSlotPreferenceId id) {
        this.id = id;
    }

    
    @Column(name="Slot", nullable=false, length=10)
    public String getSlot() {
        return this.slot;
    }
    
    public void setSlot(String slot) {
        this.slot = slot;
    }




}


