package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BackupEmpLeaveInfo generated by hbm2java
 */
@Entity
@Table(name="backup_emp_leave_info"
    ,catalog="faculty_portal"
)
public class BackupEmpLeaveInfo  implements java.io.Serializable {


     private BackupEmpLeaveInfoId id;
     private float sltaken;
     private float cltaken;
     private float dltaken;
     private float pltaken;
     private Float mltaken;

    public BackupEmpLeaveInfo() {
    }

	
    public BackupEmpLeaveInfo(BackupEmpLeaveInfoId id, float sltaken, float cltaken, float dltaken, float pltaken) {
        this.id = id;
        this.sltaken = sltaken;
        this.cltaken = cltaken;
        this.dltaken = dltaken;
        this.pltaken = pltaken;
    }
    public BackupEmpLeaveInfo(BackupEmpLeaveInfoId id, float sltaken, float cltaken, float dltaken, float pltaken, Float mltaken) {
       this.id = id;
       this.sltaken = sltaken;
       this.cltaken = cltaken;
       this.dltaken = dltaken;
       this.pltaken = pltaken;
       this.mltaken = mltaken;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="year", column=@Column(name="Year", nullable=false, length=10) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserID", nullable=false) ) } )
    public BackupEmpLeaveInfoId getId() {
        return this.id;
    }
    
    public void setId(BackupEmpLeaveInfoId id) {
        this.id = id;
    }

    
    @Column(name="SLTaken", nullable=false, precision=12, scale=0)
    public float getSltaken() {
        return this.sltaken;
    }
    
    public void setSltaken(float sltaken) {
        this.sltaken = sltaken;
    }

    
    @Column(name="CLTaken", nullable=false, precision=12, scale=0)
    public float getCltaken() {
        return this.cltaken;
    }
    
    public void setCltaken(float cltaken) {
        this.cltaken = cltaken;
    }

    
    @Column(name="DLTaken", nullable=false, precision=12, scale=0)
    public float getDltaken() {
        return this.dltaken;
    }
    
    public void setDltaken(float dltaken) {
        this.dltaken = dltaken;
    }

    
    @Column(name="PLTaken", nullable=false, precision=12, scale=0)
    public float getPltaken() {
        return this.pltaken;
    }
    
    public void setPltaken(float pltaken) {
        this.pltaken = pltaken;
    }

    
    @Column(name="MLTaken", precision=12, scale=0)
    public Float getMltaken() {
        return this.mltaken;
    }
    
    public void setMltaken(Float mltaken) {
        this.mltaken = mltaken;
    }




}


