package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,catalog="faculty_portal"
)
public class Departments  implements java.io.Serializable {


     private Integer depId;
     private String depName;
     private String shortName;

    public Departments() {
    }

	
    public Departments(String depName) {
        this.depName = depName;
    }
    public Departments(String depName, String shortName) {
       this.depName = depName;
       this.shortName = shortName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DepID", unique=true, nullable=false)
    public Integer getDepId() {
        return this.depId;
    }
    
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    
    @Column(name="DepName", nullable=false, length=30)
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }

    
    @Column(name="ShortName", length=3)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }




}


