package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="employees"
    ,catalog="faculty_portal"
)
public class Employees  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String middleName;
     private String lastName;
     private Date birthDate;
     private Date joinDate;
     private Date leaveDate;
     private Integer working;
     private String gender;
     private int depId;
     private String designation;
     private String category;
     private String type;
     private byte[] signature;
     private String salutation;

    public Employees() {
    }

	
    public Employees(String firstName, int depId, String designation, String category, String type) {
        this.firstName = firstName;
        this.depId = depId;
        this.designation = designation;
        this.category = category;
        this.type = type;
    }
    public Employees(String firstName, String middleName, String lastName, Date birthDate, Date joinDate, Date leaveDate, Integer working, String gender, int depId, String designation, String category, String type, byte[] signature, String salutation) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.joinDate = joinDate;
       this.leaveDate = leaveDate;
       this.working = working;
       this.gender = gender;
       this.depId = depId;
       this.designation = designation;
       this.category = category;
       this.type = type;
       this.signature = signature;
       this.salutation = salutation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="FirstName", nullable=false, length=15)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="MiddleName", length=15)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="LastName", length=15)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BirthDate", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="JoinDate", length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LeaveDate", length=10)
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    
    @Column(name="Working")
    public Integer getWorking() {
        return this.working;
    }
    
    public void setWorking(Integer working) {
        this.working = working;
    }

    
    @Column(name="Gender", length=2)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="DepID", nullable=false)
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }

    
    @Column(name="Designation", nullable=false, length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="Category", nullable=false, length=30)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Type", nullable=false, length=30)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="Signature")
    public byte[] getSignature() {
        return this.signature;
    }
    
    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

    
    @Column(name="Salutation", length=10)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }




}


