package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeaveInfo generated by hbm2java
 */
@Entity
@Table(name="leave_info"
    ,catalog="faculty_portal"
)
public class LeaveInfo  implements java.io.Serializable {


     private Integer lid;
     private String leaveName;
     private String leaveShortName;
     private Integer allowed;

    public LeaveInfo() {
    }

	
    public LeaveInfo(String leaveName, String leaveShortName) {
        this.leaveName = leaveName;
        this.leaveShortName = leaveShortName;
    }
    public LeaveInfo(String leaveName, String leaveShortName, Integer allowed) {
       this.leaveName = leaveName;
       this.leaveShortName = leaveShortName;
       this.allowed = allowed;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="LID", unique=true, nullable=false)
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    
    @Column(name="LeaveName", nullable=false, length=20)
    public String getLeaveName() {
        return this.leaveName;
    }
    
    public void setLeaveName(String leaveName) {
        this.leaveName = leaveName;
    }

    
    @Column(name="LeaveShortName", nullable=false, length=10)
    public String getLeaveShortName() {
        return this.leaveShortName;
    }
    
    public void setLeaveShortName(String leaveShortName) {
        this.leaveShortName = leaveShortName;
    }

    
    @Column(name="Allowed")
    public Integer getAllowed() {
        return this.allowed;
    }
    
    public void setAllowed(Integer allowed) {
        this.allowed = allowed;
    }




}


