package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SemesterWiseSubjectsId generated by hbm2java
 */
@Embeddable
public class SemesterWiseSubjectsId  implements java.io.Serializable {


     private String semester;
     private int subId;

    public SemesterWiseSubjectsId() {
    }

    public SemesterWiseSubjectsId(String semester, int subId) {
       this.semester = semester;
       this.subId = subId;
    }
   


    @Column(name="Semester", nullable=false, length=10)
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }


    @Column(name="SubID", nullable=false)
    public int getSubId() {
        return this.subId;
    }
    
    public void setSubId(int subId) {
        this.subId = subId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemesterWiseSubjectsId) ) return false;
		 SemesterWiseSubjectsId castOther = ( SemesterWiseSubjectsId ) other; 
         
		 return ( (this.getSemester()==castOther.getSemester()) || ( this.getSemester()!=null && castOther.getSemester()!=null && this.getSemester().equals(castOther.getSemester()) ) )
 && (this.getSubId()==castOther.getSubId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSemester() == null ? 0 : this.getSemester().hashCode() );
         result = 37 * result + this.getSubId();
         return result;
   }   


}


