package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SemesterWiseSubjects generated by hbm2java
 */
@Entity
@Table(name="semester_wise_subjects"
    ,catalog="faculty_portal"
)
public class SemesterWiseSubjects  implements java.io.Serializable {


     private SemesterWiseSubjectsId id;
     private Integer offered;
     private Integer semNo;

    public SemesterWiseSubjects() {
    }

	
    public SemesterWiseSubjects(SemesterWiseSubjectsId id) {
        this.id = id;
    }
    public SemesterWiseSubjects(SemesterWiseSubjectsId id, Integer offered, Integer semNo) {
       this.id = id;
       this.offered = offered;
       this.semNo = semNo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="semester", column=@Column(name="Semester", nullable=false, length=10) ), 
        @AttributeOverride(name="subId", column=@Column(name="SubID", nullable=false) ) } )
    public SemesterWiseSubjectsId getId() {
        return this.id;
    }
    
    public void setId(SemesterWiseSubjectsId id) {
        this.id = id;
    }

    
    @Column(name="Offered")
    public Integer getOffered() {
        return this.offered;
    }
    
    public void setOffered(Integer offered) {
        this.offered = offered;
    }

    
    @Column(name="SemNo")
    public Integer getSemNo() {
        return this.semNo;
    }
    
    public void setSemNo(Integer semNo) {
        this.semNo = semNo;
    }




}


