package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SlotPreference generated by hbm2java
 */
@Entity
@Table(name="slot_preference"
    ,catalog="faculty_portal"
)
public class SlotPreference  implements java.io.Serializable {


     private int userId;
     private String slot;

    public SlotPreference() {
    }

    public SlotPreference(int userId, String slot) {
       this.userId = userId;
       this.slot = slot;
    }
   
     @Id 

    
    @Column(name="UserID", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="Slot", nullable=false, length=10)
    public String getSlot() {
        return this.slot;
    }
    
    public void setSlot(String slot) {
        this.slot = slot;
    }




}


