package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubjectPreferenceSettings generated by hbm2java
 */
@Entity
@Table(name="subject_preference_settings"
    ,catalog="faculty_portal"
)
public class SubjectPreferenceSettings  implements java.io.Serializable {


     private int depId;
     private String semType;

    public SubjectPreferenceSettings() {
    }

    public SubjectPreferenceSettings(int depId, String semType) {
       this.depId = depId;
       this.semType = semType;
    }
   
     @Id 

    
    @Column(name="DepID", unique=true, nullable=false)
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }

    
    @Column(name="SemType", nullable=false, length=5)
    public String getSemType() {
        return this.semType;
    }
    
    public void setSemType(String semType) {
        this.semType = semType;
    }




}


