package hibernate.pojos;
// Generated Mar 22, 2017 6:14:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="faculty_portal"
)
public class Users  implements java.io.Serializable {


     private String userName;
     private String password;
     private int userId;
     private String userType;
     private String initials;

    public Users() {
    }

    public Users(String userName, String password, int userId, String userType, String initials) {
       this.userName = userName;
       this.password = password;
       this.userId = userId;
       this.userType = userType;
       this.initials = initials;
    }
   
     @Id 

    
    @Column(name="UserName", unique=true, nullable=false, length=10)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="Password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="UserID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="UserType", nullable=false, length=15)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

    
    @Column(name="Initials", nullable=false, length=3)
    public String getInitials() {
        return this.initials;
    }
    
    public void setInitials(String initials) {
        this.initials = initials;
    }




}


